# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "d75918a06ce58f1ae86e07b1425ec841"
name = "Moxxy App"
handle = "moxxy-app"
application_url = "https://maybe-neighbors-pilot-plate.trycloudflare.com"
embedded = true

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-04"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://maybe-neighbors-pilot-plate.trycloudflare.com/auth/callback",
  "https://maybe-neighbors-pilot-plate.trycloudflare.com/auth/shopify/callback",
  "https://maybe-neighbors-pilot-plate.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
